### ISSUE TITLE
Use Case Completion Tracker - 20 Need to be done by Monday!

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#52]
Add your test cases to Use Cases in the wiki
- [x] US01.01.01 CMPUT301W15T12Test / ClaimTest.java /testCreatingClaim()
- [x] US01.02.01
- [x] US01.03.01 
- [x] US01.04.01 CMPUT301W15T12Test / ClaimTest.java /testEditClaim()
- [x] US01.05.01 - CMPUT301W15T12Test/ClaimListControllertTest/testRemoveClaim()
- [ ] US01.06.01
- [x] US02.01.01 
- [x] US02.02.01 - CMPUT301W15T12Test/ClaimListTests/testsortClaims()  
- [x] US03.01.01  - CMPUT301W15T12Test/TagTest.java/testAddTag()
- [x] US03.02.01
- [x] US03.03.01
- [x] US04.01.01 - CMPUT301W15T12Test/ExpenseItemTests.java/testExpenseItem()  
- [x] US04.02.01 - CMPUT301W15T12Test/ExpenseItemTests.java/testCategory()  
- [x] US04.03.01 - CMPUT301W15T12Test/ExpenseItemTests.java/testCurrency()  
- [x] US04.04.01 - CMPUT301W15T12Test/ExpenseItemTests.java/testFlag()  
- [x] US04.05.01 
- [x] US04.06.01 
- [x] US04.07.01 - CMPUT301W15T12Test/ExpenseListTests.java/testdeleteExpense()
- [x] US04.08.01 
- [x] US05.01.01 - CMPUT301W15T12Test/ExpenseListTests.java/testExpenseOrder()
- [x] US06.01.01 
- [x] US06.02.01
- [x] US06.03.01
- [ ] US06.04.01 
- [x] US07.01.01 -  CMPUT301W15T12Test/ClaimActivityTests/testSubmitStatus()
- [x] US07.02.01 
- [x] US07.03.01 - CMPUT301W15T12Test/ClaimActivityTests/testReturnedStatus()
- [x] US07.04.01 - CMPUT301W15T12Test/ClaimActivityTests/testApprovedStatus()
- [x] US07.05.01 - CMPUT301W15T12Test/ClaimActivityTests/testApproverComments()
- [x] US08.01.01 
- [x] US08.02.01-   CMPUT301W15T12Test /ApproverTests.java/ testsortItem()
- [x] US08.03.01
- [x] US08.04.01
- [x] US08.05.01
- [x] US08.06.01 -   CMPUT301W15T12Test /ApproverTests.java/ testaddComment()
- [x] US08.07.01 -  CMPUT301W15T12Test / ApproverTests.java / testapproveClaim()
- [x] US08.08.01 - CMPUT301W15T12Test / ApproverTests.java / testreturnClaim()
- [x] US08.09.01 -  CMPUT301W15T12Test / ApproverTests.java/ testrestrictions()
- [ ] US09.01.01

**Comment by qsjiang** [comment]
As the TA said last Thursday, unlike previous assignment where he only looked at our test inside the wiki, this time he wants to run them himself and confirm that 50% of our tests are passing . 

So after you completed your tests, please write down the file location and the testCase function name beside the checkbox, this would help the TA marking the project.

**Comment by vanbelle** [comment]
I would've started adding these on Friday but there were still a bunch of tests with errors in them, so I couldn't check if the tests actually passed.
