### ISSUE TITLE
Still TODO

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#73]
- [x] Every method needs a comment with /** **/ so that it appears in the javadoc / Javadoc upload - Sarah
- [x] UML - Leah
- [x] Storyboard  - Leah
- [x] Mockups -Sarah
- [x] Refactoring Write up - Sarah
- [x] Bonus Video - Sarah/Megan
- [x] Power Usage Estimation - Raymond
- [x] Release Plan for future iterations
- [x] Sequence Diagram for one Use Case of a non-trivial scenario - Omar
- [x] Save picture onto server - Jim
- [x] remote geolocation stuff - Megan
- [x] Limit Picture size - Jim/Megan  
UPDATE YOUR OWN TESTS - Check that a test exists for each of these, and that it pases. 
    - [x] claim - Megan US: ~~01.01-01.05, 07.01~~, ~~07.02~~, ~~07.03-07.05~~
    - [x] Approving/returning - Sarah US: ~~8.01-08.09,02.01~~
    - [x] expense item/list - Raymond US: ~~05.01, 04.01-04.08~~
    - [x] tags - Raymond US: ~~03.01~~, ~~03.02~~,~~03.03~~
    - [x] claim list - Jim US: ~~01.06~~,~~02.02~~
    - [x] Login tests - Sarah No user stories
    - [x] Geolocation Tests - Sarah US: ~~01.07, 02.03,04.09, 10.01~~, 10.02
    - [x] Geolocation Tests - Megan US: ~~10.02~~- ~~10.03~~
    - [x] Picture Tests - Megan US: 06.01, ~~06.02~~,06.03,06.04
- [x] save file when there is no internet - Jim
- [x] error handling for internet - Jim
- [x] adding menu item to save to server - Sarah/Jim

**Comment by vanbelle** [comment]
@LeahGabrielle  @megsum @IchigoKIl @qsjiang 
I updated the portion of who has to check what test, I couldnt quite remember who had done what, so if i made a mistake just let me know.

**Comment by vanbelle** [comment]
@LeahGabrielle @megsum @IchigoKIl @qsjiang 

One of the reasons the activity tests werent running was that people werent passing the activity an intent. So i fixed one of the ones i was working, and will push it so that you can see how i passed it along. This should make most of the activity tests pretty easy to fix.

CMPUT301W15T12/ApproverItemActivity/testitemUI()

**Comment by megsum** [comment]
@Pengwin-man please do the Sequence Diagram for one Use Case of a non-trivial scenario. If you want to match it with the story board, do log in, add claim, add item to claim, submit claim for approval. If you have any questions, let us know!

**Comment by vanbelle** [comment]
Can someone else check to make sure they can see the Video Link? It works for me, but since its on my account that doesnt necessarily mean everyone can view it.

**Comment by Pengwin-man** [comment]
@vanbelle : I can see the video just fine

**Comment by Pengwin-man** [comment]
@megsum i can do log-in, add claim and add item to claim.  where do you want me to submit them?

**Comment by vanbelle** [comment]
In the wiki should be fine

**Comment by Pengwin-man** [comment]
do you want me to make a new category for the sequence diagrams?

**Comment by LeahGabrielle** [comment]
@Pengwin-man You could either make a new page, or put it with the UML I would say.
